[package]
name = "pomodoros"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.16"
termion = "1.5"
serde_json = "1.0"
serde = { version = "1.0.130", features = ["derive"] }